### ISSUE TITLE
Confluent schema registry support.

### ISSUE THREAD

**Issue by vasilii-avdiushkin** [anodot/daria#19]
Hi! From the wiki:
> Allowed values SOURCE (schema is present in data itself), INLINE (specify schema in kafkaConfigBean.dataFormatConfig.avroSchema parameter)

The way I understood that, the schema is supported only in plaintext format.
Is it possible to provide only a schema-registry URL the way it is done with the other consumers? In our case, it would be benefitial in order to have a single place for schema maintanence (https://docs.confluent.io/current/schema-registry/index.html).

**Comment by dariakharlan** [comment]
Hi. Schema registry is supported, docs are updated.
Example of config:
```json
{
  "conf.dataFormatConfig.avroSchemaSource": "REGISTRY",
  "conf.dataFormatConfig.schemaRegistryUrls": ["https://url/to/the/registry"],
  "conf.dataFormatConfig.schemaLookupMode": "AUTO"
}
```

Please note that `conf.dataFormatConfig.confname` is a new format of the config starting with version `1.6.0`. In older versions, you should use `kafkaConfigBean.dataFormatConfig.confname`

@vasilii-avdiushkin may I ask, which company you represent?

**Comment by dixel** [comment]
Sure! I am representing FREE NOW at the moment (https://free-now.com/).
